version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: Borgir
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

volumes:
  database-data:
